# Generated by Django 4.2.29 on 2026-03-18 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='分类描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='用户的自然语言问题', verbose_name='问题')),
                ('question_keywords', models.JSONField(blank=True, default=list, help_text='从问题中提取的关键词', verbose_name='问题关键词')),
                ('sql_query', models.TextField(help_text='对应的SQL查询语句', verbose_name='SQL查询语句')),
                ('description', models.TextField(blank=True, default='', help_text='SQL语句的详细说明', verbose_name='描述说明')),
                ('tags', models.JSONField(blank=True, default=list, help_text='用于检索的标签列表', verbose_name='标签')),
                ('table_names', models.JSONField(blank=True, default=list, help_text='SQL涉及的数据库表名', verbose_name='涉及表名')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='被查询使用的次数', verbose_name='使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_items', to='knowledge_base.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '知识问答',
                'verbose_name_plural': '知识问答',
                'ordering': ['-use_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_query', models.TextField(verbose_name='用户查询')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='相似度分数')),
                ('is_matched', models.BooleanField(default=False, verbose_name='是否匹配成功')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='查询时间')),
                ('matched_knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_histories', to='knowledge_base.knowledgeqa', verbose_name='匹配的知识')),
            ],
            options={
                'verbose_name': '查询历史',
                'verbose_name_plural': '查询历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeqa',
            index=models.Index(fields=['question'], name='knowledge_b_questio_b88f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeqa',
            index=models.Index(fields=['is_active'], name='knowledge_b_is_acti_b9ea5c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeqa',
            index=models.Index(fields=['category'], name='knowledge_b_categor_5360f4_idx'),
        ),
    ]
